// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/nos-services": {
    params: {};
  };
  "/notre-structure": {
    params: {};
  };
  "/notre-procede": {
    params: {};
  };
  "/junior-entreprises": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/mentions-legales": {
    params: {};
  };
  "/api/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/nos-services" | "/notre-structure" | "/notre-procede" | "/junior-entreprises" | "/contact" | "/mentions-legales" | "/api/contact";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/nos-services.tsx": {
    id: "routes/nos-services";
    page: "/nos-services";
  };
  "routes/notre-structure.tsx": {
    id: "routes/notre-structure";
    page: "/notre-structure";
  };
  "routes/notre-procede.tsx": {
    id: "routes/notre-procede";
    page: "/notre-procede";
  };
  "routes/junior-entreprises.tsx": {
    id: "routes/junior-entreprises";
    page: "/junior-entreprises";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/mentions-legales.tsx": {
    id: "routes/mentions-legales";
    page: "/mentions-legales";
  };
  "routes/api/contact.tsx": {
    id: "routes/api/contact";
    page: "/api/contact";
  };
};